#Qdrant as vector db
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    # ports:
    #  - 6333:6333/tcp
    #  - 6334:6334/tcp
    healthcheck:
      test:
        - CMD-SHELL
        - bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1
      interval: 60s
      timeout: 5s
      retries: 3
    volumes:
      - ./qdrant_data:/qdrant/storage
    profiles:
      - local
    labels:
      - traefik.enable=true
      - traefik.http.routers.qdrant.rule=PathPrefix(`/qdrant`)
      - traefik.http.routers.qdrant.entrypoints=web
      - traefik.http.routers.qdrant.tls=false
      - traefik.http.services.qdrant-service.loadbalancer.server.port=6333
      - traefik.http.services.qdrant-service.loadbalancer.server.port=6334
