#apache tika server with ocr
services:
  tika:
    image: logicalspark/docker-tikaserver:latest
    container_name: tika
    #   ports:
    #     - 9998:9998/tcp
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - bash -c ':> /dev/tcp/127.0.0.1/9998' || exit 1
      interval: 60s
      timeout: 5s
      retries: 3
    labels:
      - traefik.enable=true
      - traefik.http.routers.tika.rule=PathPrefix(`/tika`)
      - traefik.http.routers.tika.entrypoints=web
      - traefik.http.routers.tika.tls=false
      - traefik.http.services.tika-service.loadbalancer.server.port=9998
